export const cardProfileData = [
  {
    id: "1",
    cardName: "Verve-1",
    currency: "NGN",
    expiration: 40,
    binPrefix: "50611234",
    dateCreated: "11/10/2024  23:21:03",
    cardScheme: "Verve",
    description: "This is a test description",
    branchBlacklist: "Head Office",
  },
  {
    id: "2",
    cardName: "Verve-2",
    currency: "NGN",
    expiration: 40,
    binPrefix: "50611234",
    dateCreated: "11/10/2024  23:21:03",
    cardScheme: "MasterCard",
    description: "This is a test description",
    branchBlacklist: "Head Office",
  },
  {
    id: "3",
    cardName: "Verve-3",
    currency: "NGN",
    expiration: 40,
    binPrefix: "50611234",
    dateCreated: "11/10/2024  23:21:03",
    cardScheme: "Visa",
    description: "This is a test description",
    branchBlacklist: "Head Office",
  },
];
